### ISSUE TITLE
Lecture 4 filename is incorrect

### ISSUE THREAD

**Issue by ClarSco** [pigworker/CS316-16#1]
The file [Lec4.hs](https://github.com/pigworker/CS316-16/blob/master/lectures/Lec4.hs) should be renamed to [Lec04.hs](https://github.com/pigworker/CS316-16/blob/master/lectures/Lec04.hs) in line with the link on the [class webpage](https://personal.cis.strath.ac.uk/conor.mcbride/Marx/?page=CS316/events/2016-09-30-lecture-04) as that link is currently broken.

**Comment by jmchapman** [comment]
renamed. thanks.
